# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: consultation.etalab.gouv.fr
baseurl: ""
url: "https://consultation.etalab.gouv.fr"
description: Des outils de consultations en ligne pour les administrations

# see https://jekyllrb.com/docs/continuous-integration/
exclude: [vendor, app.json, Gemfile.lock]

collections:
  outil:
    output: true
  usage:
    output: true

defaults:
  -
    scope:
      path: ""	# means "all files"
      type: outil	# targets a collection
    values:
      layout: outil
      default_logo: 

  -
    scope:
      path: ""	# means "all files"
      type: usage	# targets a collection
    values:
      layout: usage
  -
    scope:
      path: ""  # means "all files"
    values:
      layout: default

markdown: kramdown
