#!/bin/bash

echo "Start deploy"
ssh -tq consultation@ "bash -lc 'cd /home//consultation.gouv.fr && git pull'"
ssh -tq consultation@ "bash -lc 'cd /home//consultation.gouv.fr && bundle exec jekyll doctor'"
ssh -tq consultation@ "bash -lc 'cd /home//consultation.gouv.fr && bundle exec jekyll build'"
echo "Deployed Successfully!"

exit 0
