#!/bin/bash

USER="consultation"
HOST="pprod.consultation.etalab.gouv.fr"

echo "Start deploy"

ssh -tq ${USER}@${HOST} "bash -lc 'cd consultation.gouv.fr && git pull && bundle exec jekyll doctor && bundle exec jekyll build'"
rc=$?

if [ $? == 0 ] ; then
  echo "Deploy successful"
else
  echo "Deploy failed"
fi

exit $rc
